### ISSUE TITLE
Automatic Library Integration

### ISSUE THREAD

**Issue by eskape** [mancuniancol/plugin.video.eztv#1]
I have added a bunch of favourite tv shows in EZTV Viewer. 
Also enabled the Automatic (Kodi) Library Integration for every show via Context menu.

Will EZTV Viewer scan/search all my favourite tv shows and update my kodi library when new episodes are available? And how often does that happen?

Or do I have to enable the Automatic Integration Service for that? I tried that last week, but somehow EZTV Viewer adds ALL new tv show episodes to my kodi library. So besides my favourite tv shows it added ALL other tv shows.

**Comment by mancuniancol** [comment]
The viewer checks every time that kodi starts. But, if you keep your kodi on, you should activate the automatic service too.

**Comment by mancuniancol** [comment]
It seems to be a bug. Could you share your debug log of kodi. You can use pastebin.com.

**Comment by eskape** [comment]
Yesterday I enabled the Automatic Integration Service and disabled Persistent update @8. 
Now I'm seeing 7 tv shows folders which I did not add as favourite. 
I'm looking at the kodi logs right now (openelec install). But I don't see any plugin.video.eztv debug info. Can you help me setting up the debug info from plugin.video.eztv in logs?

**Comment by mancuniancol** [comment]
Yes, you need to enable debug mode in Kodi
